/*
 * This file is generated by jOOQ.
 */
package world.good2go.db.jooq


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl

import world.good2go.db.jooq.tables.FlywaySchemaHistory
import world.good2go.db.jooq.tables.Helloworld


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Good2go : SchemaImpl("good2go", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>good2go</code>
         */
        val GOOD2GO: Good2go = Good2go()
    }

    /**
     * The table <code>good2go.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>good2go.HelloWorld</code>.
     */
    val HELLOWORLD: Helloworld get() = Helloworld.HELLOWORLD

    public override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    public override fun getTables(): List<Table<*>> = listOf(
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
        Helloworld.HELLOWORLD
    )
}
