/*
 * This file is generated by jOOQ.
 */
package world.good2go.db.jooq.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import world.good2go.db.jooq.tables.FlywaySchemaHistory
import world.good2go.db.jooq.tables.Helloworld
import world.good2go.db.jooq.tables.records.FlywaySchemaHistoryRecord
import world.good2go.db.jooq.tables.records.HelloworldRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val KEY_HELLOWORLD_PRIMARY: UniqueKey<HelloworldRecord> = Internal.createUniqueKey(Helloworld.HELLOWORLD, DSL.name("KEY_HelloWorld_PRIMARY"), arrayOf(Helloworld.HELLOWORLD.ID), true)
