/*
 * This file is generated by jOOQ.
 */
package world.good2go.db.jooq.tables.references


import world.good2go.db.jooq.tables.FlywaySchemaHistory
import world.good2go.db.jooq.tables.Helloworld



/**
 * The table <code>good2go.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>good2go.HelloWorld</code>.
 */
val HELLOWORLD: Helloworld = Helloworld.HELLOWORLD
