/*
 * This file is generated by jOOQ.
 */
package world.good2go.db.jooq.tables.records


import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.UpdatableRecordImpl

import world.good2go.db.jooq.tables.FlywaySchemaHistory


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FlywaySchemaHistoryRecord() : UpdatableRecordImpl<FlywaySchemaHistoryRecord>(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY), Record10<Int?, String?, String?, String?, String?, Int?, String?, LocalDateTime?, Int?, Byte?> {

    open var installedRank: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var version: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var type: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var script: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var checksum: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var installedBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var installedOn: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var executionTime: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var success: Byte?
        set(value): Unit = set(9, value)
        get(): Byte? = get(9) as Byte?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    public override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    public override fun fieldsRow(): Row10<Int?, String?, String?, String?, String?, Int?, String?, LocalDateTime?, Int?, Byte?> = super.fieldsRow() as Row10<Int?, String?, String?, String?, String?, Int?, String?, LocalDateTime?, Int?, Byte?>
    public override fun valuesRow(): Row10<Int?, String?, String?, String?, String?, Int?, String?, LocalDateTime?, Int?, Byte?> = super.valuesRow() as Row10<Int?, String?, String?, String?, String?, Int?, String?, LocalDateTime?, Int?, Byte?>
    public override fun field1(): Field<Int?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK
    public override fun field2(): Field<String?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.VERSION
    public override fun field3(): Field<String?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.DESCRIPTION
    public override fun field4(): Field<String?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.TYPE
    public override fun field5(): Field<String?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SCRIPT
    public override fun field6(): Field<Int?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.CHECKSUM
    public override fun field7(): Field<String?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_BY
    public override fun field8(): Field<LocalDateTime?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_ON
    public override fun field9(): Field<Int?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.EXECUTION_TIME
    public override fun field10(): Field<Byte?> = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS
    public override fun component1(): Int? = installedRank
    public override fun component2(): String? = version
    public override fun component3(): String? = description
    public override fun component4(): String? = type
    public override fun component5(): String? = script
    public override fun component6(): Int? = checksum
    public override fun component7(): String? = installedBy
    public override fun component8(): LocalDateTime? = installedOn
    public override fun component9(): Int? = executionTime
    public override fun component10(): Byte? = success
    public override fun value1(): Int? = installedRank
    public override fun value2(): String? = version
    public override fun value3(): String? = description
    public override fun value4(): String? = type
    public override fun value5(): String? = script
    public override fun value6(): Int? = checksum
    public override fun value7(): String? = installedBy
    public override fun value8(): LocalDateTime? = installedOn
    public override fun value9(): Int? = executionTime
    public override fun value10(): Byte? = success

    public override fun value1(value: Int?): FlywaySchemaHistoryRecord {
        set(0, value)
        return this
    }

    public override fun value2(value: String?): FlywaySchemaHistoryRecord {
        set(1, value)
        return this
    }

    public override fun value3(value: String?): FlywaySchemaHistoryRecord {
        set(2, value)
        return this
    }

    public override fun value4(value: String?): FlywaySchemaHistoryRecord {
        set(3, value)
        return this
    }

    public override fun value5(value: String?): FlywaySchemaHistoryRecord {
        set(4, value)
        return this
    }

    public override fun value6(value: Int?): FlywaySchemaHistoryRecord {
        set(5, value)
        return this
    }

    public override fun value7(value: String?): FlywaySchemaHistoryRecord {
        set(6, value)
        return this
    }

    public override fun value8(value: LocalDateTime?): FlywaySchemaHistoryRecord {
        set(7, value)
        return this
    }

    public override fun value9(value: Int?): FlywaySchemaHistoryRecord {
        set(8, value)
        return this
    }

    public override fun value10(value: Byte?): FlywaySchemaHistoryRecord {
        set(9, value)
        return this
    }

    public override fun values(value1: Int?, value2: String?, value3: String?, value4: String?, value5: String?, value6: Int?, value7: String?, value8: LocalDateTime?, value9: Int?, value10: Byte?): FlywaySchemaHistoryRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    constructor(installedRank: Int? = null, version: String? = null, description: String? = null, type: String? = null, script: String? = null, checksum: Int? = null, installedBy: String? = null, installedOn: LocalDateTime? = null, executionTime: Int? = null, success: Byte? = null): this() {
        this.installedRank = installedRank
        this.version = version
        this.description = description
        this.type = type
        this.script = script
        this.checksum = checksum
        this.installedBy = installedBy
        this.installedOn = installedOn
        this.executionTime = executionTime
        this.success = success
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    constructor(value: world.good2go.db.jooq.tables.pojos.FlywaySchemaHistory?): this() {
        if (value != null) {
            this.installedRank = value.installedRank
            this.version = value.version
            this.description = value.description
            this.type = value.type
            this.script = value.script
            this.checksum = value.checksum
            this.installedBy = value.installedBy
            this.installedOn = value.installedOn
            this.executionTime = value.executionTime
            this.success = value.success
            resetChangedOnNotNull()
        }
    }
}
